
import { World, Faction, Artefact, Creature, Quest, Ally, NarrativeArc } from './types';

export const FACTIONS: Faction[] = [
  {
    id: 'guardians',
    name: 'L’ORDRE DES GARDIENS DU TEMPS',
    nature: 'Caste d’êtres forgés dans la chronomatière par les Architectes Stellaires.',
    ideology: 'Préserver l’équilibre du Temps, protéger les lignes temporelles, empêcher l’Entropie de dévorer le multivers.',
    organisation: 'Le Gardien Absolu (Onyzuka), Gardiens Primaires (Disparus), Gardiens Mineurs (Échos).',
    symbols: ['◯', '🪶', '🌀'],
    relations: 'Hostiles aux Enfants de l’Entropie. Méfiants envers les mortels.',
    lore: 'Forgés dans les feux de Virellion, ils sont le dernier rempart contre le néant.'
  },
  {
    id: 'entropy_children',
    name: 'LES ENFANTS DE L’ENTROPIE',
    nature: 'Créatures nées de la singularité entropique.',
    ideology: 'Tout doit retourner au néant. Le Temps est une anomalie.',
    organisation: 'Seraphon (Avatar), Fractales Vivantes, Ombres Chroniques.',
    symbols: ['⚡', '⚫', '❄️'],
    relations: 'Ennemis jurés des Gardiens. Dévorent les mondes instables.',
    lore: 'Ils ne cherchent pas à régner, mais à effacer l\'existence même.'
  },
  {
    id: 'temporal_echoes',
    name: 'LES ÉCHOS TEMPORELS',
    nature: 'Fragments d’anciens Gardiens, coincés entre deux réalités.',
    ideology: 'Variable selon leur corruption (Purs, Instables, Corrompus).',
    organisation: 'Silhouettes errantes dans les rifts temporels.',
    symbols: ['🌫️', '⏳', '⛓️'],
    relations: 'Alliés ou obstacles selon leur état de résonance.',
    lore: 'Ce sont les fantômes de ceux qui ont échoué avant vous.'
  },
  {
    id: 'stellar_architects',
    name: 'LES ARCHITECTES STELLAIRES',
    nature: 'Civilisation disparue, créatrice des Gardiens.',
    ideology: 'Le Temps doit être structuré. Le chaos doit être contenu.',
    organisation: 'Hiérarchie géométrique parfaite (Disparue).',
    symbols: ['⬢', '☉', '♾️'],
    relations: 'Vénérés comme des créateurs. Leurs plans guident Onyzuka.',
    lore: 'Ils ont laissé le Codex comme guide avant de transcender la matière.'
  }
];

export const ARTEFACTS: Artefact[] = [
  {
    id: 'codex',
    name: 'LE CODEX DES ÂGES',
    nature: 'Livre cosmique vivant, contenant les lois du Temps.',
    functions: ['Stabilise les lignes temporelles', 'Archive les civilisations', 'Permet la création de Gardiens'],
    powers: 'Source de pouvoir ultime, capable de réécrire les cycles de l\'Entropie.',
    icon: '📜',
    // Added missing lore string
    lore: 'Le Nexus de toute connaissance, dont les pages respirent au rythme des éons de chronomatière.'
  },
  {
    id: 'rings',
    name: 'LES ANNEAUX DU TEMPS',
    nature: 'Portails géants, conscients, mi‑métal mi‑énergie.',
    functions: ['Voyage temporel', 'Communication entre Gardiens', 'Stockage de mémoire'],
    powers: 'Permet une synchronisation instantanée entre les mondes du Codex.',
    icon: '🌀',
    // Added missing lore string
    lore: 'Des conduits circulaires reliant les lointaines nébuleuses aux forges centrales des Architectes.'
  },
  {
    id: 'blades',
    name: 'LES LAMES DU TEMPS',
    nature: 'Rubans métalliques d’Onyzuka, capables de se transformer.',
    functions: ['Lames tranchantes', 'Fouets énergétiques', 'Boucliers', 'Propulseurs', 'Analyseurs'],
    powers: 'Extensions vivantes de l\'armure de combat, adaptables à toute menace.',
    icon: '🗡️',
    // Added missing lore string
    lore: 'Lames mutables forgées dans le néant absolu pour trancher les fils de l\'entropie rampante.'
  },
  {
    id: 'heart',
    name: 'LE CŒUR ENTROPIQUE',
    nature: 'Fragment vivant de la singularité.',
    functions: ['Dévore la chronomatière', 'Corrompt les Gardiens', 'Déforme les lignes temporelles'],
    powers: 'L\'antithèse de l\'ordre, cherchant à dissoudre toute structure.',
    icon: '🔥',
    // Added missing lore string
    lore: 'Un battement de chaos pur qui menace de réduire le Codex et ses mondes en poussière stellaire.'
  },
  {
    id: 'forge',
    name: 'LA FORGE VIVANTE',
    nature: 'Lieu où les Gardiens sont créés.',
    functions: ['Manipule la chronomatière', 'Imprime les mémoires', 'Forge les armures'],
    powers: 'Le berceau de la volonté des Architectes Stellaires.',
    icon: '⚙️',
    // Added missing lore string
    lore: 'L\'athanor cosmique où la volonté pure rencontre la chronomatière malléable pour enfanter des héros.'
  }
];

export const CREATURES: Creature[] = [
  {
    id: 'spirales_vivantes',
    name: 'LES SPIRALES VIVANTES',
    nature: 'Rubans d’énergie sensibles.',
    behavior: 'Curieux, pacifiques, attirés par Onyzuka.',
    worldId: 'virellion',
    icon: '🌀',
    lore: 'Nées du premier soupir des Architectes, ces filaments de lumière liquide tissent la reality entre les nébuleuses indigo de Virellion. Elles reconnaissent en Onyzuka un frère d\'âme, vibrant en harmonie avec ses rubans métalliques comme pour lui rappeler sa propre origine divine.'
  },
  {
    id: 'golems_chrono',
    name: 'LES GOLEMS DE CHRONOMATIÈRE',
    nature: 'Créatures forgées par les Architectes.',
    behavior: 'Protecteurs, agressifs envers les intrus.',
    worldId: 'kharon',
    icon: '🗿',
    lore: 'Massives sentinelles d\'obsidienne et d\'acier stellaire, ces golems ne sont pas de simples gardes mais la mémoire vivante des forges de Kharon. Chaque pierre qui les compose est gravée d\'un théorème temporel ancien, faisant d\'eux des bibliothèques de combat quasi indestructibles.'
  },
  {
    id: 'leviathans_lumiere',
    name: 'LES LÉVIATHANS DE LUMIÈRE',
    nature: 'Immenses créatures océaniques d’énergie.',
    behavior: 'Pacifiques sauf si perturbés.',
    worldId: 'elyndra',
    icon: '🐋',
    lore: 'Majestueux gardiens des eaux d\'Aether, ces colosses de données liquides archivent les émotions de chaque civilisation disparue. Leur chant n\'est pas un simple son, mais un flux de souvenirs purifiés qui empêche les courants d\'Elyndra de stagner dans la mélancolie du passé.'
  },
  {
    id: 'ombres_chroniques',
    name: 'LES OMBRES CHRONIQUES',
    nature: 'Entités absorbant la lumière.',
    behavior: 'Chasse en meute, silencieuse.',
    worldId: 'noxaris',
    icon: '👥',
    lore: 'Ces cicatrices mouvantes sur la réalité représentent l\'absence même de Temps. Nées là où Seraphon a effacé l\'existence, elles traquent la lumière car elles sont la faim du Néant personnifiée, cherchant à dévorer la chronomatière pour étendre le silence absolu de Noxaris.'
  },
  {
    id: 'solariens',
    name: 'LES SOLARIENS',
    nature: 'Êtres humanoïdes faits de lumière.',
    behavior: 'Sages, mais méfiants envers les Gardiens.',
    worldId: 'solara-prime',
    icon: '☀️',
    lore: 'Ayant transcendé le besoin d\'une forme physique, les Solariens vivent en synchronie totale avec le soleil artificiel de Solara Prime. Ils considèrent les Gardiens comme des outils archaïques mais nécessaires, observant Onyzuka avec une curiosité froide née de cycles d\'immobilité radieuse.'
  },
  {
    id: 'fractales_vivantes',
    name: 'LES FRACTALES VIVANTES',
    nature: 'Créatures géométriques auto‑répliquantes.',
    behavior: 'Imprévisibles, parfois hostiles.',
    worldId: 'aetheryon',
    icon: '⬢',
    lore: 'Paradoxes biologiques nés du Labyrinthe, ces créatures représentent toutes les itérations possibles d\'un même organisme. Elles apparaissent et disparaissent au gré de la perspective de l\'observateur, défiant les lois de la biologie par leur reproduction purement logique et mathématique.'
  },
  {
    id: 'enfants_entropie_creatures',
    name: 'LES ENFANTS DE L’ENTROPIE',
    nature: 'Créatures nées du néant.',
    behavior: 'Dévorent la chronomatière, corrompent les Gardiens.',
    worldId: 'entropy-core',
    icon: '💀',
    lore: 'Hérauts apocalyptiques de la fin des cycles, ces êtres n\'ont aucune individualité. Ils sont les extensions griffues de la singularité, nés pour détricoter les fils du Codex et ramener toute structure à son état originel de chaos silencieux au cœur de l\'Entropie.'
  }
];

export const ALLIES: Ally[] = [
  { id: 'kalder', name: 'Kalder', role: 'Forgeron de l\'Âme', icon: '🔧', lore: 'Répare l\'armure d\'Onyzuka with devotion.', outcome: 'Meurt en héros pour sceller la Forge.' },
  { id: 'elyia', name: 'Elya', role: 'Guide Spirituelle', icon: '✨', lore: 'Offre des visions de futurs possibles.', outcome: 'Devient la nouvelle archiviste du Codex.' },
  { id: 'nox', name: 'Nox', role: 'Traître Repenti', icon: '🎭', lore: 'Ancien serviteur de l\'Entropie cherchant la rédemption.', outcome: 'Sacrifice final pour protéger Onyzuka.' },
  { id: 'solarion', name: 'Solarion', role: 'Rival Solaire', icon: '⚔️', lore: 'Guerrier fier de Solara Prime.', outcome: 'Offre la Couronne après un duel mémorable.' },
  { id: 'aeth', name: 'Aeth', role: 'Logique Pure', icon: '🧩', lore: 'Entité mathématique du Labyrinthe.', outcome: 'Fusion temporaire pour résoudre le Paradoxe Final.' },
  { id: 'lyria', name: 'Lyria', role: 'L\'Étincelle', icon: '💖', lore: 'Première humaine rencontrée par Onyzuka.', outcome: 'Lui enseigne l\'importance de la transmission.' }
];

export const QUESTS: Quest[] = [
  { id: 'q1', title: 'Spirale de l’Éveil', worldId: 'virellion', description: 'Premier affrontement contre Seraphon.', objective: 'Récupérer le premier fragment.', outcome: 'L’éveil d’Onyzuka est complet.' },
  { id: 'q2', title: 'La Forge du Passé', worldId: 'kharon', description: 'Réparation des rubans métalliques.', objective: 'Découvrir le secret de Seraphon.', outcome: 'L’Arsenal est stabilisé.' },
  { id: 'q3', title: 'L’Océan des Visions', worldId: 'elyndra', description: 'Épreuve spirituelle dans les eaux d’Aether.', objective: 'Obtenir la Lame d’Elyndra.', outcome: 'La vision du futur est clarifiée.' },
  { id: 'q4', title: 'Le Monde Sans Lumière', worldId: 'noxaris', description: 'Traverser l’obscurité totale.', objective: 'Gérer la trahison de Nox.', outcome: 'Le fragment de l’Ombre est sécurisé.' },
  { id: 'q5', title: 'Le Duel Solaire', worldId: 'solara-prime', description: 'Combat rituel pour la souveraineté.', objective: 'Gagner la Couronne de Solara.', outcome: 'Solarion reconnaît votre authority.' },
  { id: 'q6', title: 'Le Labyrinthe Fractal', worldId: 'aetheryon', description: 'Épreuve de logique pure.', objective: 'Extraire le Fractal d’Aetheryon.', outcome: 'La géométrie du Temps est comprise.' },
  { id: 'q7', title: 'Le Jugement Final', worldId: 'entropy-core', description: 'Bataille finale au cœur du néant.', objective: 'Vaincre Seraphon définitivement.', outcome: 'Restauration complète du Codex.' },
  { id: 'q8', title: 'Souvenirs de Nébuleuse', worldId: 'virellion', description: 'Filtrer les résidus de chronomatière.', objective: 'Collecter 500 CM.', outcome: 'La nébuleuse brille avec une nouvelle pureté.' },
  { id: 'q9', title: 'Le Chant des Particules', worldId: 'virellion', description: 'Accorder la harpe de lumière.', objective: 'Synchroniser la fréquence de base.', outcome: 'Les créatures de Virellion chantent à nouveau.' },
  { id: 'q10', title: 'Lueurs Interdites', worldId: 'iridia', description: 'Exploration des grottes de cristal.', objective: 'Trouver le prisme perdu.', outcome: 'La lumière se courbe pour vous obéir.' },
  { id: 'q11', title: 'Le Spectre de l’Aube', worldId: 'iridia', description: 'Défendre le grand prisme.', objective: 'Repousser les ombres de Noxaris.', outcome: 'L\'aurore d\'Iridia est sauvée.' },
  { id: 'q12', title: 'Réflexions Brisées', worldId: 'iridia', description: 'Réassembler le miroir d\'âme.', objective: 'Vaincre votre double entropique.', outcome: 'Votre identité de Gardien est renforcée.' },
  { id: 'q13', title: 'Le Marteau des Titans', worldId: 'kharon', description: 'Ranimer la flamme éternelle.', objective: 'Activer le soufflet stellaire.', outcome: 'Les forges reprennent leur vacarme sacré.' },
  { id: 'q14', title: 'Le Secret de l’Acier', worldId: 'kharon', description: 'Apprendre les techniques des Architectes.', objective: 'Forger une extension de ruban.', outcome: 'Votre portée d\'attaque est augmentée.' },
  { id: 'q15', title: 'Cœur de Fusion', worldId: 'kharon', description: 'Stabiliser le noyau instable.', objective: 'Rééquilibrer la température.', outcome: 'Kharon ne s\'effondrera pas aujourd\'hui.' },
  { id: 'q16', title: 'Le Maître de l’Horloge', worldId: 'mechanus', description: 'Réparer le Grand Echappement.', objective: 'Aligner 12 pignons synchrones.', outcome: 'Le temps local cesse de bégayer.' },
  { id: 'q17', title: 'Rouages de la Destinée', worldId: 'mechanus', description: 'Infiltrer le centre de calcul.', objective: 'Hacker l\'IA de Mechanus.', outcome: 'Vous avez accès aux fichiers secrets.' },
  { id: 'q18', title: 'Poussière d’Engrenage', worldId: 'mechanus', description: 'Nettoyer la rouille entropique.', objective: 'Éliminer 50 parasites.', outcome: 'La machine tourne sans friction.' },
  { id: 'q19', title: 'Profondeurs de l’Esprit', worldId: 'elyndra', description: 'Plonger dans la fosse des souvenirs.', objective: 'Récupérer une pensée pure.', outcome: 'Une nouvelle loi du Temps est révélée.' },
  { id: 'q20', title: 'Marées d’Aether', worldId: 'elyndra', description: 'Naviguer sur les courants changeants.', objective: 'Atteindre le temple englouti.', outcome: 'Le savoir des anciens est à vous.' },
  { id: 'q21', title: 'Symphonie Liquide', worldId: 'elyndra', description: 'Accorder les vagues.', objective: 'Résoudre le puzzle harmonique.', outcome: 'L\'océan se calme à votre approche.' },
  { id: 'q22', title: 'Racines de l’Éternité', worldId: 'verdant-core', description: 'Sauver l\'Arbre des Âges.', objective: 'Purifier les lianes corrompues.', outcome: 'La forêt bourdonne de vie.' },
  { id: 'q23', title: 'La Graine Perdue', worldId: 'verdant-core', description: 'Planter le futur.', objective: 'Trouver la graine de chronomatière.', outcome: 'Un nouveau bosquet commence à pousser.' },
  { id: 'q24', title: 'Chasseurs de Sève', worldId: 'verdant-core', description: 'Protéger la faune locale.', objective: 'Vaincre les prédateurs de fer.', outcome: 'L\'écosystème est stabilisé.' },
  { id: 'q25', title: 'Le Murmure du Vide', worldId: 'noxaris', description: 'Écouter le silence.', objective: 'Identifier la source du cri.', outcome: 'Vous comprenez la douleur de Seraphon.' },
  { id: 'q26', title: 'Sentinelles de l’Ombre', worldId: 'noxaris', description: 'Passer inaperçu.', objective: 'Traverser sans être détecté.', outcome: 'Votre furtivité est grandement améliorée.' },
  { id: 'q27', title: 'L’Étincelle Finale', worldId: 'noxaris', description: 'Apporter la lumière.', objective: 'Allumer les 3 balises.', outcome: 'Noxaris connaît une brève aurore.' },
  { id: 'q28', title: 'Calcul Infini', worldId: 'tensor-reach', description: 'Résoudre le paradoxe de Tensor.', objective: 'Compléter l\'équation finale.', outcome: 'Les lois de la physique vous obéissent.' },
  { id: 'q29', title: 'Vecteurs de Guerre', worldId: 'tensor-reach', description: 'Simuler le combat final.', objective: 'Gagner 10 batailles virtuelles.', outcome: 'Vos réflexes sont optimisés.' },
  { id: 'q30', title: 'Données Perdues', worldId: 'tensor-reach', description: 'Restaurer le serveur central.', objective: 'Récupérer les blocs de mémoire.', outcome: 'Le passé est enfin clair.' },
  { id: 'q31', title: 'Lumière de l’Empire', worldId: 'solara-prime', description: 'Restaurer la gloire passée.', objective: 'Nettoyer les dômes d\'or.', outcome: 'Solara brille sur les mondes voisins.' },
  { id: 'q32', title: 'La Garde Solaire', worldId: 'solara-prime', description: 'Entraînement avec les échos.', objective: 'Parer 100 attaques.', outcome: 'Votre bouclier est impénétrable.' },
  { id: 'q33', title: 'L’Appel du Roi', worldId: 'solara-prime', description: 'Audience avec l\'Ancien.', objective: 'Convaincre l\'IA souveraine.', outcome: 'L\'alliance est scellée.' },
  { id: 'q34', title: 'L’Impasse Logique', worldId: 'aetheryon', description: 'Sortir du cercle vicieux.', objective: 'Trouver la sortie du labyrinthe.', outcome: 'Votre esprit transcende la géométrie.' },
  { id: 'q35', title: 'Formes de Pensée', worldId: 'aetheryon', description: 'Matérialiser vos idées.', objective: 'Créer un pont de fractales.', outcome: 'La matière n\'est qu\'une idée.' },
  { id: 'q36', title: 'Le Point de Vue', worldId: 'aetheryon', description: 'Changer la perspective.', objective: 'Voir le labyrinthe d\'en haut.', outcome: 'Rien n\'est impossible.' },
  { id: 'q37', title: 'Au Bord du Gouffre', worldId: 'entropy-core', description: 'Rester stable face au néant.', objective: 'Maintenir votre intégrité à 100%.', outcome: 'Vous êtes prêt pour la fin.' },
  { id: 'q38', title: 'Le Cri de la Singularité', worldId: 'entropy-core', description: 'Fermer la faille.', objective: 'Utiliser le Codex sur le noyau.', outcome: 'L\'entropie recule d\'un pas.' },
  { id: 'q39', title: 'L’Adieu au Gardien', worldId: 'entropy-core', description: 'Honorer les morts.', objective: 'Placer une fleur de Calyx dans le vide.', outcome: 'Les âmes des anciens reposent en paix.' },
  { id: 'q40', title: 'L’Ascenseur Magnétique', worldId: 'world-12', description: 'Réactiver les rails de Zion.', objective: 'Reconnecter les aimants.', outcome: 'Le transport est fluide.' },
  { id: 'q41', title: 'Le Marché des Échos', worldId: 'world-12', description: 'Échanger des souvenirs.', objective: 'Obtenir la clé de Zion.', outcome: 'Les portes de la ville s\'ouvrent.' },
  { id: 'q42', title: 'Vapeurs de Cuivre', worldId: 'world-12', description: 'Réparer les conduits.', objective: 'Stopper les fuites de gaz.', outcome: 'L\'air est respirable.' },
  { id: 'q43', title: 'L’Appétit de l’Abîme', worldId: 'world-13', description: 'Nourrir le vide with de la chronomatière.', objective: 'Sacrifier 1000 CM.', outcome: 'L\'abîme s\'endort pour un cycle.' },
  { id: 'q44', title: 'Au Fond de la Gorge', worldId: 'world-13', description: 'Récupérer l\'éclat noir.', objective: 'Plonger sans peur.', outcome: 'L\'ombre est votre alliée.' },
  { id: 'q45', title: 'Le Silence des Étoiles', worldId: 'world-13', description: 'Trouver la dernière étoile.', objective: 'Protéger la lumière mourante.', outcome: 'Une nouvelle constellation naît.' },
  { id: 'q46', title: 'Station Fantôme', worldId: 'world-14', description: 'Réveiller les automates.', objective: 'Insérer la cellule d\'énergie.', outcome: 'La station reprend vie.' },
  { id: 'q47', title: 'L’Héritage Interdit', worldId: 'world-14', description: 'Accéder à la zone 51-T.', objective: 'Décoder le mot de passe.', outcome: 'Des prototypes secrets sont révélés.' },
  { id: 'q48', title: 'Vide Sidéral', worldId: 'world-14', description: 'Sortie extra-véhiculaire.', objective: 'Réparer l\'antenne externe.', outcome: 'Le signal est clair.' },
  { id: 'q49', title: 'Nuages de Pensées', worldId: 'world-15', description: 'Matérialiser un rêve.', objective: 'Imaginer un bouclier puissant.', outcome: 'Votre protection est doublée.' },
  { id: 'q50', title: 'Le Brouillard d’Oros', worldId: 'world-15', description: 'Dissiper les doutes.', objective: 'Traverser sans se perdre.', outcome: 'Votre volonté est de fer.' },
  { id: 'q51', title: 'Échos d’Argent', worldId: 'world-15', description: 'Parler aux ancêtres.', objective: 'Écouter le message caché.', outcome: 'Le secret de la fusion est révélé.' },
  { id: 'q52', title: 'Nuit de Néon', worldId: 'world-16', description: 'Restaurer l\'énergie de la ville.', objective: 'Activer les transformateurs.', outcome: 'La fête peut continuer.' },
  { id: 'q53', title: 'Pluie de Photons', worldId: 'world-16', description: 'Collecter l\'énergie céleste.', objective: 'Remplir 10 condensateurs.', outcome: 'Vos batteries sont pleines.' },
  { id: 'q54', title: 'Le Roi du Zenith', worldId: 'world-16', description: 'Gagner la course de vitesse.', objective: 'Atteindre le sommet en 60s.', outcome: 'Vous êtes le plus rapide.' },
  { id: 'q55', title: 'Cœur de Fer', worldId: 'world-17', description: 'Éteindre l\'incendie du noyau.', objective: 'Utiliser la glace d\'Aether.', outcome: 'La planète refroidit.' },
  { id: 'q56', title: 'Mineurs d’Éternité', worldId: 'world-17', description: 'Extraire le métal pur.', objective: 'Collecter 5 tonnes de minerai.', outcome: 'Votre armure est indestructible.' },
  { id: 'q57', title: 'Chaleur Infernale', worldId: 'world-17', description: 'Survivre à la fournaise.', objective: 'Atteindre le centre de la mine.', outcome: 'Le feu ne vous brûle plus.' },
  { id: 'q58', title: 'Le Parfum du Temps', worldId: 'world-18', description: 'Ouvrir les pétales.', objective: 'Utiliser la fréquence 432Hz.', outcome: 'La fleur libère sa connaissance.' },
  { id: 'q59', title: 'Pollen Mortel', worldId: 'world-18', description: 'Neutraliser les toxines.', objective: 'Purifier l\'air ambiant.', outcome: 'Le jardin est à nouveau sûr.' },
  { id: 'q60', title: 'Sève Dorée', worldId: 'world-18', description: 'Récolter l\'élixir.', objective: 'Remplir la fiole de cristal.', outcome: 'Votre santé est restaurée.' },
  { id: 'q61', title: 'Sables du Passé', worldId: 'world-19', description: 'Trouver la cité perdue.', objective: 'Suivre les traces de pas.', outcome: 'Les ruines sont découvertes.' },
  { id: 'q62', title: 'Tempête de Verre', worldId: 'world-19', description: 'Trouver un abri.', objective: 'Tenir 2 minutes sous l\'orage.', outcome: 'Vous avez appris à résister.' },
  { id: 'q63', title: 'Mirages d’Obsidienne', worldId: 'world-19', description: 'Distinguer le vrai du faux.', objective: 'Détruire les illusions.', outcome: 'Votre vision est parfaite.' },
  { id: 'q64', title: 'Le Bibliothécaire', worldId: 'world-20', description: 'Trouver le livre des morts.', objective: 'Chercher dans l\'allée 7.', outcome: 'Le destin de Seraphon est écrit.' },
  { id: 'q65', title: 'Le Silence de la Lecture', worldId: 'world-20', description: 'Éviter les automates.', objective: 'Atteindre le bureau central.', outcome: 'La carte du multivers est à vous.' },
  { id: 'q66', title: 'Encres de Lumière', worldId: 'world-20', description: 'Réécrire un chapitre.', objective: 'Changer un événement mineur.', outcome: 'Le présent est légèrement modifié.' },
  { id: 'q67', title: 'L’Oeil du Cyclope', worldId: 'world-21', description: 'Stabiliser le vortex.', objective: 'Lancer 3 ancres temporelles.', outcome: 'Le calme revient sur Vortex-9.' },
  { id: 'q68', title: 'Gravité Zéro', worldId: 'world-21', description: 'S\'adapter au chaos.', objective: 'Combattre sans appui.', outcome: 'Votre agilité est légendaire.' },
  { id: 'q69', title: 'Matière Noire', worldId: 'world-21', description: 'Étudier la décomposition.', objective: 'Scanner 5 anomalies.', outcome: 'Le néant n\'a plus de secrets.' },
  { id: 'q70', title: 'Prisme de Réalité', worldId: 'world-22', description: 'Réaligner les facettes.', objective: 'Faire correspondre les couleurs.', outcome: 'Le monde retrouve sa forme.' },
  { id: 'q71', title: 'Reflets Trompeurs', worldId: 'world-22', description: 'Passer à travers le miroir.', objective: 'Entrer dans la dimension miroir.', outcome: 'Vous pouvez traverser les murs.' },
  { id: 'q72', title: 'Lumière Polarisée', worldId: 'world-22', description: 'Concentrer le rayon.', objective: 'Viser la cible centrale.', outcome: 'Le fragment est libéré.' },
  { id: 'q73', title: 'L’Enclume Solaire', worldId: 'world-23', description: 'Recevoir le marteau.', objective: 'Lever l\'objet sacré.', outcome: 'Votre force est décuplée.' },
  { id: 'q74', title: 'Météores en Feu', worldId: 'world-23', description: 'Détruire les menaces.', objective: 'Détruire 10 astéroïdes.', outcome: 'Le ciel est dégagé.' },
  { id: 'q75', title: 'Rivières de Magma', worldId: 'world-23', description: 'Refroidir la coulée.', objective: 'Détourner le magma.', outcome: 'Le village est sauvé.' },
  { id: 'q76', title: 'Mer de Plasma', worldId: 'world-24', description: 'Traverser le golfe.', objective: 'Construire un bateau d\'énergie.', outcome: 'Le voyage continue.' },
  { id: 'q77', title: 'Foudre de Cobalt', worldId: 'world-24', description: 'Capturer l\'éclair.', objective: 'Utiliser le paratonnerre.', outcome: 'Votre arme est électrifiée.' },
  { id: 'q78', title: 'Ionisation Totale', worldId: 'world-24', description: 'Surcharger le système.', objective: 'Atteindre 1,21 GW.', outcome: 'Le portail s\'ouvre.' },
  { id: 'q79', title: 'Le Chant du Monolithe', worldId: 'world-25', description: 'Écouter la vibration.', objective: 'Méditer pendant 1 minute.', outcome: 'Votre paix intérieure est totale.' },
  { id: 'q80', title: 'Aiguille de Cristal', worldId: 'world-25', description: 'Monter au sommet.', objective: 'Escalader sans tomber.', outcome: 'Le monde est à vos pieds.' },
  { id: 'q81', title: 'Harmonie Parfaite', worldId: 'world-25', description: 'Jouer la mélodie du monde.', objective: 'Appuyer sur les 7 touches.', outcome: 'Le cristal s\'illumine.' },
  { id: 'q82', title: 'Le Berceau du Vide', worldId: 'world-26', description: 'Assister à une naissance.', objective: 'Protéger l\'oeuf stellaire.', outcome: 'Une nouvelle étoile est née.' },
  { id: 'q83', title: 'Calme Absolu', worldId: 'world-26', description: 'Ne rien faire.', objective: 'Attendre l\'éclosion.', outcome: 'La patience est une vertu.' },
  { id: 'q84', title: 'Germe de Lumière', worldId: 'world-26', description: 'Planter le germe.', objective: 'Trouver le sol fertile.', outcome: 'Le futur est assuré.' },
  { id: 'q85', title: 'La Faille d’Émeraude', worldId: 'world-27', description: 'Fermer la blessure.', objective: 'Coudre le tissu de la réalité.', outcome: 'Le gaz toxique disparaît.' },
  { id: 'q86', title: 'Venin Temporel', worldId: 'world-27', description: 'Trouver l\'antidote.', objective: 'Mélanger les 3 herbes.', outcome: 'Vous êtes immunisé au poison.' },
  { id: 'q87', title: 'L’Ascension Finale', worldId: 'world-37', description: 'Franchir le point zéro.', objective: 'Fusionner avec le Codex.', outcome: 'Vous êtes le Temps.' }
];

export const NARRATIVE_ARCS: NarrativeArc[] = [
  { id: 'main', title: 'La Reconstruction du Codex', stages: ['Éveil', 'Codex Brisé', 'Voyage des 7 Mondes', 'Confrontation', 'Fusion', 'Renaissance'] },
  { id: 'villain', title: 'La Chute de Seraphon', stages: ['Corruption', 'Manipulation', 'Destruction', 'Absorption', 'Combat Final', 'Annihilation'] },
  { id: 'emotional', title: 'De la Solitude à la Transmission', stages: ['Isolement', 'Rencontre (Lyria)', 'Héritage', 'Doute', 'Acceptation', 'Nouvel Ordre'] },
  { id: 'cosmic', title: 'La Maladie du Temps', stages: ['Distorsions', 'Répétitions', 'Échos Instables', 'Effondrement', 'Guérison'] }
];

export const WORLDS: World[] = [
  {
    id: 'virellion',
    name: 'Virellion',
    description: 'Le berceau mystique d\'Onyzuka. Une nébuleuse vivante baignée de chronomatière éthérée.',
    palette: ['#4c1d95', '#0f766e', '#1e1b4b'],
    fragmentName: 'Spirale de Virellion',
    order: 1,
    biome: 'Nebula',
    category: 'NEBULA',
    variant: 'STABLE',
    status: 'unlocked',
    keyPoints: ['Anneau fracturé', 'Spirale de Virellion', 'Champ de particules sensibles'],
    ambiance: 'Mystique, organique, naissance du héros.',
    history: 'Née du premier soupir des Architectes, Virellion n\'est pas une simple planète mais une pépinière de probabilités cosmiques.'
  },
  {
    id: 'iridia',
    name: 'Iridia',
    description: 'Un prisme stellaire où la lumière se décompose en spectres solides.',
    palette: ['#d946ef', '#0ea5e9', '#ffffff'],
    fragmentName: 'Prisme d’Iridia',
    order: 2,
    biome: 'Liquid Light',
    category: 'WORLD',
    variant: 'STABLE',
    status: 'locked',
    keyPoints: ['Cascades chromatiques', 'Forêt de verre', 'Échos spectraux'],
    ambiance: 'Éclatante, fragile, kaléidoscopique.',
    history: 'Iridia servait de lentille focale pour les Architectes, purifiant la lumière brute des étoiles avant de l\'injecter dans les veines du Temps.'
  },
  {
    id: 'kharon',
    name: 'Kharon',
    description: 'Une forge astéroïdale titanesque vibrant du vacarme des marteaux des Architectes.',
    palette: ['#44403c', '#ef4444', '#78350f'],
    fragmentName: 'Forge de Kharon',
    order: 3,
    biome: 'Metallic Forge',
    category: 'WORLD',
    variant: 'STABLE',
    status: 'locked',
    keyPoints: ['Forge vivante', 'Archives des Architectes', 'Lave de chronomatière'],
    ambiance: 'Industrielle, sacrée, brutale.',
    history: 'Autrefois une naine blanche mourante, Kharon fut capturée pour devenir le cœur industriel de la création.'
  },
  {
    id: 'mechanus',
    name: 'Mechanus',
    description: 'Une grille infinie d’engrenages et de pistons à l’échelle planétaire.',
    palette: ['#334155', '#f97316', '#0f172a'],
    fragmentName: 'Pignon de l’Éternité',
    order: 4,
    biome: 'Metallic Forge',
    category: 'WORLD',
    variant: 'STABLE',
    status: 'locked',
    keyPoints: ['Horloge centrale', 'Vapeurs de cuivre', 'Labyrinthe de fer'],
    ambiance: 'Mécanique, implacable, rythmée.',
    history: 'Le régulateur de la causalité. Chaque rotation d’engrenage sur Mechanus définit une seconde dans la réalité matérielle.'
  },
  {
    id: 'elyndra',
    name: 'Elyndra',
    description: 'Une étendue infinie de lumière liquide, un océan onirique de sagesse oubliée.',
    palette: ['#0ea5e9', '#06b6d4', '#e0f2fe'],
    fragmentName: 'Lame d’Elyndra',
    order: 5,
    biome: 'Liquid Light',
    category: 'WORLD',
    variant: 'STABLE',
    status: 'locked',
    keyPoints: ['Temple submergé', 'Îles flottantes', 'Faune luminescente'],
    ambiance: 'Calme, hypnotique, spirituelle.',
    history: 'Ici, les mémoires se dissolvent dans l\'eau d\'Aether pour être purifiées par les courants du Temps.'
  },
  {
    id: 'verdant-core',
    name: 'Verdant Core',
    description: 'Une jungle bio-mécanique où la chronomatière a pris racine sous forme de lianes d\'énergie.',
    palette: ['#166534', '#14532d', '#86efac'],
    fragmentName: 'Graine de Vie Chronique',
    order: 6,
    biome: 'Nebula',
    category: 'WORLD',
    variant: 'STABLE',
    status: 'locked',
    keyPoints: ['Arbre des Âges', 'Pollution entropique', 'Lumière filtrée'],
    ambiance: 'Organique, étouffante, vibrante.',
    history: 'Une expérience de croissance temporelle où les Architectes ont tenté de faire "pousser" des lignes temporelles.'
  },
  {
    id: 'noxaris',
    name: 'Noxaris',
    description: 'Une prison de ténèbres absolues, un cimetière stellaire dévorant la lumière.',
    palette: ['#171717', '#450a0a', '#000000'],
    fragmentName: 'Obscurité de Noxaris',
    order: 7,
    biome: 'Total Darkness',
    category: 'WORLD',
    variant: 'FRACTURED',
    status: 'locked',
    keyPoints: ['Ombres chroniques', 'Structures fractales', 'Lumière absorbée'],
    ambiance: 'Oppressante, silencieuse, entropique.',
    history: 'Le Jardin des Murmures, corrompu par Seraphon en une encre de plomb étouffante.'
  },
  {
    id: 'tensor-reach',
    name: 'Tensor Reach',
    description: 'Un espace de calcul pur où la réalité est définie par des vecteurs de probabilité.',
    palette: ['#4f46e5', '#818cf8', '#312e81'],
    fragmentName: 'Vecteur de Tensor',
    order: 8,
    biome: 'Fractal Labyrinth',
    category: 'WORLD',
    variant: 'STABLE',
    status: 'locked',
    keyPoints: ['Grille logique', 'Données flottantes', 'Gravité scalaire'],
    ambiance: 'Froide, abstraite, mathématique.',
    history: 'Le processeur central de l\'Anneau des Âges, calculant les trajectoires des mondes pour éviter les collisions temporelles.'
  },
  {
    id: 'solara-prime',
    name: 'Solara Prime',
    description: 'Une citadelle de cristal et d\'or nichée au cœur d\'un astre artificiel majestueux.',
    palette: ['#facc15', '#ea580c', '#fbbf24'],
    fragmentName: 'Couronne de Solara',
    order: 9,
    biome: 'Radiant City',
    category: 'WORLD',
    variant: 'STABLE',
    status: 'locked',
    keyPoints: ['Archives stellaires', 'Tours dorées', 'Anneaux solaires'],
    ambiance: 'Majestueuse, divine, éclatante.',
    history: 'Le phare central diffusant le signal de Synchronie qui maintenait la stabilité du multivers.'
  },
  {
    id: 'aetheryon',
    name: 'Aetheryon',
    description: 'Un labyrinthe fractal où la géométrie se tord et se multiplie à l’infini.',
    palette: ['#d946ef', '#6366f1', '#a855f7'],
    fragmentName: 'Fractal d’Aetheryon',
    order: 10,
    biome: 'Fractal Labyrinth',
    category: 'WORLD',
    variant: 'RESTORED',
    status: 'locked',
    keyPoints: ['Labyrinthe vivant', 'Géométrie impossible', 'Gravité variable'],
    ambiance: 'Psychédélique, déroutante, mathématique.',
    history: 'Une prison logique conçue pour enfermer les paradoxes trop dangereux pour le reste de l’existence.'
  },
  {
    id: 'entropy-core',
    name: 'Cœur de l’Entropie',
    description: 'Le point d\'ancrage du Néant. Une singularité affamée marquant la fin des cycles.',
    palette: ['#000000', '#dc2626', '#1a1a1a'],
    fragmentName: 'Cœur Entropique',
    order: 11,
    biome: 'Singularity',
    category: 'CORE',
    variant: 'FRACTURED',
    status: 'locked',
    keyPoints: ['Seraphon', 'Entropie', 'Distorsions temporelles'],
    ambiance: 'Apocalyptique, instable, finale.',
    history: 'Le point de rupture final, là où la chronomatière se dissout pour retourner à l\'état de pur néant.'
  },
  { id: 'world-12', name: 'Zion-4', description: 'Une mégapole de cuivre suspendue dans le vide.', palette: ['#b45309', '#78350f', '#000000'], fragmentName: 'Bobine de Zion', order: 12, biome: 'Radiant City', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Rails magnétiques', 'Dômes de verre'], ambiance: 'Urbaine, archaïque.', history: 'Un hub commercial pour les échos égarés.' },
  { id: 'world-13', name: 'Abyssal Maw', description: 'Un gouffre vivant dévorant les étoiles mortes.', palette: ['#1e1b4b', '#000000', '#312e81'], fragmentName: 'Oeil du Vide', order: 13, biome: 'Total Darkness', category: 'WORLD', variant: 'CORRUPTED', status: 'locked', keyPoints: ['Horizons des événements', 'Cris stellaires'], ambiance: 'Terreur pure.', history: 'Un dépotoir cosmique devenu conscient.' },
  { id: 'world-14', name: 'Chronos Station', description: 'Un anneau orbital découpé par des lasers de temps.', palette: ['#cbd5e1', '#64748b', '#0f172a'], fragmentName: 'Synchroniseur', order: 14, biome: 'Metallic Forge', category: 'RING', variant: 'DORMANT', status: 'locked', keyPoints: ['Laboratoires vides', 'Hologrammes'], ambiance: 'Stérile, nostalgique.', history: 'Le centre de recherche des Architectes sur l\'immortalité.' },
  { id: 'world-15', name: 'Mist of Oros', description: 'Une nébuleuse de gaz d\'argent où les pensées deviennent réalité.', palette: ['#e2e8f0', '#94a3b8', '#1e293b'], fragmentName: 'Vapeur d’Esprit', order: 15, biome: 'Nebula', category: 'NEBULA', variant: 'STABLE', status: 'locked', keyPoints: ['Fantômes de gaz', 'Échos'], ambiance: 'Onirique.', history: 'Un réservoir de rêves collectifs.' },
  { id: 'world-16', name: 'Neon Zenith', description: 'Une ville flottante éclairée par des gaz nobles.', palette: ['#ec4899', '#3b82f6', '#000000'], fragmentName: 'Tube de Néon', order: 16, biome: 'Radiant City', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Publicités holographiques', 'Pluie de photons'], ambiance: 'Cyber-cosmique.', history: 'Une colonie de plaisir oubliée.' },
  { id: 'world-17', name: 'Iron Star', description: 'Une étoile solide faite de plaques de blindage.', palette: ['#451a03', '#78350f', '#000000'], fragmentName: 'Noyau de Fer', order: 17, biome: 'Metallic Forge', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Tunnels de mine', 'Chaleur intense'], ambiance: 'Suffocante.', history: 'La source de métal primaire du multivers.' },
  { id: 'world-18', name: 'Calyx', description: 'Une fleur de la taille d\'un système solaire.', palette: ['#f472b6', '#db2777', '#500724'], fragmentName: 'Pétale de Temps', order: 18, biome: 'Liquid Light', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Pollen de lumière', 'Sève dorée'], ambiance: 'Parfumée, mortelle.', history: 'Un pollinisateur de réalités.' },
  { id: 'world-19', name: 'Obsidian Reach', description: 'Un désert de sable noir sous un ciel sans soleil.', palette: ['#171717', '#000000', '#262626'], fragmentName: 'Grain d’Eternité', order: 19, biome: 'Total Darkness', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Tempêtes de verre', 'Ruines noires'], ambiance: 'Désolée.', history: 'Un monde dont le temps a été "aspiré".' },
  { id: 'world-20', name: 'Grand Archive', description: 'Des rayons de bibliothèque s’étendant sur des années-lumière.', palette: ['#d97706', '#92400e', '#000000'], fragmentName: 'Parchemin Sacré', order: 20, biome: 'Radiant City', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Livres de lumière', 'Automates archivistes'], ambiance: 'Studieuse.', history: 'Le savoir total du multivers.' },
  { id: 'world-21', name: 'Vortex-9', description: 'Un tourbillon de matière en décomposition.', palette: ['#7f1d1d', '#b91c1c', '#000000'], fragmentName: 'Eclat de Vortex', order: 21, biome: 'Singularity', category: 'CORE', variant: 'CORRUPTED', status: 'locked', keyPoints: ['Gravité inversée', 'Flashs'], ambiance: 'Violente.', history: 'Une erreur de calcul des Architectes.' },
  { id: 'world-22', name: 'Shattered Prism', description: 'Des éclats de réalité flottant dans un vide miroitant.', palette: ['#06b6d4', '#ec4899', '#ffffff'], fragmentName: 'Fragment de Réfraction', order: 22, biome: 'Fractal Labyrinth', category: 'WORLD', variant: 'FRACTURED', status: 'locked', keyPoints: ['Reflets trompeurs', 'Portails'], ambiance: 'Confuse.', history: 'Une ligne temporelle brisée en mille morceaux.' },
  { id: 'world-23', name: 'Titan’s Anvil', description: 'Une enclume de pierre volcanique battue par des météores.', palette: ['#1c1917', '#44403c', '#ef4444'], fragmentName: 'Marteau Solaire', order: 23, biome: 'Metallic Forge', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Impacts', 'Rivières de lave'], ambiance: 'Enfer minéral.', history: 'Où les boucliers des Gardiens sont testés.' },
  { id: 'world-24', name: 'Plasma Gulf', description: 'Une mer de feu bleu sans rivage.', palette: ['#2563eb', '#3b82f6', '#dbeafe'], fragmentName: 'Écume Ionisée', order: 24, biome: 'Nebula', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Vagues de chaleur', 'Foudres'], ambiance: 'Électrique.', history: 'La batterie du multivers.' },
  { id: 'world-25', name: 'Crystal Monolith', description: 'Une aiguille de cristal transperçant les nuages.', palette: ['#f1f5f9', '#94a3b8', '#ffffff'], fragmentName: 'Pointe Harmonique', order: 25, biome: 'Liquid Light', category: 'WORLD', variant: 'RESTORED', status: 'locked', keyPoints: ['Vibrations', 'Chant spectral'], ambiance: 'Angélique.', history: 'Un résonateur de paix.' },
  { id: 'world-26', name: 'Void Cradle', description: 'Une sphère de silence où les étoiles naissent.', palette: ['#000000', '#1e1b4b', '#ffffff'], fragmentName: 'Germe Stellaire', order: 26, biome: 'Singularity', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Nébuleuses foetales', 'Calme'], ambiance: 'Maternelle.', history: 'L\'utérus de l\'univers.' },
  { id: 'world-27', name: 'Emerald Rift', description: 'Une faille de gaz vert émeraude toxique.', palette: ['#059669', '#064e3b', '#000000'], fragmentName: 'Cristal de Venin', order: 27, biome: 'Nebula', category: 'NEBULA', variant: 'CORRUPTED', status: 'locked', keyPoints: ['Nuages acides', 'Lueurs'], ambiance: 'Vénéneuse.', history: 'Une zone de quarantaine entropique.' },
  { id: 'world-28', name: 'Sulfur Peak', description: 'Une montagne jaune crachant des fumées amères.', palette: ['#eab308', '#854d0e', '#000000'], fragmentName: 'Soufre Ancien', order: 28, biome: 'Metallic Forge', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Geysers', 'Cristaux jaunes'], ambiance: 'Ocre, lourde.', history: 'Une mine de catalyseurs temporels.' },
  { id: 'world-29', name: 'Shattered Clockwork', description: 'Des engrenages géants flottant sans ordre.', palette: ['#b45309', '#000000', '#78350f'], fragmentName: 'Ressort Brisé', order: 29, biome: 'Metallic Forge', category: 'WORLD', variant: 'FRACTURED', status: 'locked', keyPoints: ['Débris', 'Tic-tac irrégulier'], ambiance: 'Mélancolique.', history: 'Une horloge qui a cessé de battre.' },
  { id: 'world-30', name: 'Neural Network', description: 'Un réseau de neurones de la taille d\'une planète.', palette: ['#4f46e5', '#ec4899', '#000000'], fragmentName: 'Synapse d’Or', order: 30, biome: 'Fractal Labyrinth', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Signaux électriques', 'Mémoires'], ambiance: 'Intelligente.', history: 'L\'IA qui gère les flux de chronomatière.' },
  { id: 'world-31', name: 'Singing Sands', description: 'Un désert où le vent joue une symphonie infinie.', palette: ['#fbbf24', '#f59e0b', '#000000'], fragmentName: 'Note de Sable', order: 31, biome: 'Nebula', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Dunes musicales', 'Mirages'], ambiance: 'Mélodique.', history: 'Le conservatoire du vent cosmique.' },
  { id: 'world-32', name: 'Cobalt Depths', description: 'Un océan de mercure bleu sous pression.', palette: ['#1d4ed8', '#1e3a8a', '#000000'], fragmentName: 'Perle de Cobalt', order: 32, biome: 'Liquid Light', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Fosses', 'Lumières froides'], ambiance: 'Écrasante.', history: 'Où les secrets les plus lourds sont cachés.' },
  { id: 'world-33', name: 'The Gilded Void', description: 'Un espace vide rempli de poussière d\'or.', palette: ['#fbbf24', '#000000', '#ffffff'], fragmentName: 'Lingot de Temps', order: 33, biome: 'Radiant City', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Nuages dorés', 'Reflets'], ambiance: 'Luxueuse.', history: 'Le trésor des Architectes.' },
  { id: 'world-34', name: 'Moon of Melancholy', description: 'Une lune grise pleurant des larmes de glace.', palette: ['#94a3b8', '#1e293b', '#ffffff'], fragmentName: 'Larme de Glace', order: 34, biome: 'Total Darkness', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Cratères gelés', 'Froid'], ambiance: 'Triste.', history: 'Un sanctuaire pour les émotions perdues.' },
  { id: 'world-35', name: 'Star-Forge 01', description: 'La première usine à étoiles.', palette: ['#ef4444', '#f97316', '#000000'], fragmentName: 'Allumeur Stellaire', order: 35, biome: 'Metallic Forge', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Creusets', 'Rayons X'], ambiance: 'Infernale.', history: 'Le berceau de la lumière.' },
  { id: 'world-36', name: 'Liquid Eternity', description: 'Une fontaine de jouvence cosmique.', palette: ['#22d3ee', '#0891b2', '#ffffff'], fragmentName: 'Coupe d’Eternité', order: 36, biome: 'Liquid Light', category: 'WORLD', variant: 'STABLE', status: 'locked', keyPoints: ['Cascades infinies', 'Vapeur'], ambiance: 'Rafraîchissante.', history: 'La source de l\'énergie vitale des Gardiens.' },
  { id: 'world-37', name: 'Zero Point', description: 'L’origine et la fin. Le silence blanc.', palette: ['#ffffff', '#000000', '#f8fafc'], fragmentName: 'Le Point Zero', order: 37, biome: 'Singularity', category: 'CORE', variant: 'RESTORED', status: 'locked', keyPoints: ['Le Néant', 'L\'Absolu'], ambiance: 'Paix totale.', history: 'Là où tout a commencé. Là où tout se finira.' }
];
